C
C unbinned likelihood fit  of Xi(1530)  only
C
      PROGRAM MAIN
      IMPLICIT NONE
      INTEGER MXDATA,NDATA,NPARM
      PARAMETER(MXDATA=1000000)
      DOUBLE PRECISION X,Y,DY
      COMMON /USER/ X(MXDATA),Y(MXDATA),DY(MXDATA),NDATA
      INTEGER I, J, IDATA, ICYCLE
      EXTERNAL FCN

      PARAMETER(NPARM=1)
      CHARACTER*10 PNAM
      INTEGER NPRM
      DOUBLE PRECISION VSTRT, STP, ARGLIS
      COMMON/PARS/ VSTRT(NPARM), STP(NPARM),ARGLIS(10),
     &     NPRM(NPARM), PNAM(NPARM) 

      INTEGER IERFLG
      DATA NPRM /   1  /
      DATA PNAM / 'K'  /
      DATA VSTRT/ 9.D-3 /
      DATA STP  /   0.0001 /

      NDATA=3
      X(1) = 1696.D0
      X(2) = 1862.D0
      X(3) = 2027.D0

C      Y(1)  = 1.1000D0
C      DY(1) = 0.04000D0
C      Y(2) = 1.22D0
C      DY(2) = 0.04D0

      Y(1)  = 1.170670D0
      Y(2)  = 1.292175D0
      Y(3)  = 1.442387D0

      DY(1) =  3.846793D-02
      DY(2) =  4.533589D-02
      DY(3) =  4.994992D-02

      open(unit=22,file='lsq_e.dat',
     &     status='unknown',form='formatted')

      CALL MNINIT(5,6,7) 

      DO I=1,NPARM
        CALL MNPARM(NPRM(I),PNAM(I),VSTRT(I),STP(I),0.D0,0.D0,IERFLG) 
        IF (IERFLG .NE. 0)  THEN 
          WRITE (6,'(A,I)')  ' UNABLE TO DEFINE PARAMETER NO.',I 
          STOP 
        ENDIF  
      ENDDO


      CALL MNSETI('xicst')

      
      ARGLIS(1) = 1. 
      CALL MNEXCM(FCN, 'CALL FCN', ARGLIS ,1,IERFLG,0) 

      ARGLIS(1) = 2. 
      CALL MNEXCM(FCN,'SET PRINT', ARGLIS ,1,IERFLG,0) 
      CALL MNEXCM(FCN,'SET STR', ARGLIS ,1,IERFLG,0) 
      CALL MNEXCM(FCN,'MIGRAD', ARGLIS ,0,IERFLG,0) 
      ARGLIS(1) = 3.
      CALL MNEXCM(FCN,'CALL FCN', ARGLIS , 1,IERFLG,0) 
      CALL MNEXCM(FCN,'STOP ', 0.D0,0,IERFLG,0)

      CLOSE(22)
      STOP
      END


      SUBROUTINE FCN(NPAR,GIN,F,U,IFLAG)
C      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INTEGER IFLAG,NPAR
      DOUBLE PRECISION U,GIN,F
      DIMENSION U(*),GIN(*)
      INTEGER MXDATA,NDATA,NPARM,I,NPOINTS
      PARAMETER(MXDATA=1000000)
      DOUBLE PRECISION X,Y,DY
      COMMON /USER/ X(MXDATA),Y(MXDATA),DY(MXDATA),NDATA
      DOUBLE PRECISION FUN,SUM,SQRT,DEXP,BWG,BWG2,C1,C2,HIGHM
      DOUBLE PRECISION GCM,GCS,GCG
      PARAMETER(NPARM=1)
      CHARACTER*10 PNAM
      INTEGER NPRM
      DOUBLE PRECISION VSTRT, STP, ARGLIS
      COMMON/PARS/ VSTRT(NPARM), STP(NPARM),ARGLIS(10),
     &     NPRM(NPARM), PNAM(NPARM)
      DOUBLE PRECISION EU,FOLD
      DIMENSION EU(NPARM)
      DOUBLE PRECISION EMAT,EPLUS,EMINUS,EPARAB,GLOBCC,LOW,HIGH
      DIMENSION EMAT(NPARM,NPARM)
      CHARACTER*10 CHNAM
      DOUBLE PRECISION VAL,ERROR,BND1,BND2
      INTEGER IVARBL
      INTEGER NSTEPS,J
      DOUBLE PRECISION LEFT,RIGHT,VAR,INTEGRAL,STEP


 100  SUM=0.D0
      DO I=1,NDATA
        SUM = SUM + (U(1)*X(I)+1.D0-U(1)*1530.D0-Y(I))**2/DY(I)/DY(I)
      END DO
      F=SUM
      IF (IFLAG.EQ.3) THEN
        DO I=1,NPARM
          CALL MNPOUT (I,CHNAM,VAL,ERROR,BND1,BND2,IVARBL)
          WRITE(22,1003)I,CHNAM,VAL,ERROR,BND1,BND2,IVARBL
 1003     FORMAT(7X,I5,1X,A10,4G20.10,I5)
        ENDDO
        CALL MNEMAT(EMAT,NPARM)
        DO I=1,NPARM
          WRITE(22,1002)(EMAT(I,J),J=1,NPARM)
 1002     FORMAT(8x,8G20.10)
        ENDDO
  
      ENDIF
      RETURN
      END        
      
