(TeX-add-style-hook "analysis"
 (function
  (lambda ()
    (LaTeX-add-labels
     "eq:decaychain"
     "fig:lambdac"
     "tab:lamc"
     "eq:bi"
     "eq:dmass"
     "fig:lamcst"
     "tab:fit"
     "eq:rsb"
     "eq:lsb"
     "fig:wrong"
     "tab:fit1"
     "sec:fit"
     "fig:gamma"
     "eq:fitfinal"
     "eq:gamma"
     "fig:fakes"
     "eq:cut"
     "eq:fraction"
     "fig:mcsic"
     "fig:sicpl"
     "fig:sic0"
     "fig:nonres"
     "eq:efficiency"
     "fig:peterson1"
     "eq:dm1"
     "eq:dm2"
     "eq:dm12"))))

