(TeX-add-style-hook "intro_lena"
 (function
  (lambda ()
    (LaTeX-add-labels
     "eq:family"
     "eq:CKM"
     "tab:glue"
     "eq:alphaqcd"
     "sec:quarkmodel"
     "eq:young"
     "eq:su3"
     "eq:su6"
     "eq:su2"
     "eq:rules"
     "eq:su3su2"
     "eq:wf"
     "fig:fundamental"
     "fig:mult"
     "eq:su4"
     "eq:dsu3"
     "eq:dsu2"
     "eq:dsu3su2"
     "eq:fb"
     "eq:oscillator"
     "eq:rholambda"
     "eq:zamena"
     "eq:ikarl"
     "rab:copley"
     "tab:masses"))))

